wisp:
   version: '1.0.0'

   envelope:
      enabled: true
      include_debug_info: true

   throttle:
      enabled: true
      limit: 60
      interval: 60
      strategy: ip

   bearer:
      enabled: true
      decoder: App\Security\TestBearerDecoder

when@test:
   wisp:
      throttle:
         enabled: false
